version: "3.4"

services:
  reverse-proxy:
    container_name: "sharedshoppinglist-reverse_proxy"
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./compose/certbot/www/:/var/www/certbot/:ro
      - ./compose/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    container_name: "sharedshoppinglist-certbot"
    image: certbot/certbot:latest
    volumes:
      - ./compose/certbot/www/:/var/www/certbot/:rw # files that need to be served to authenticate the server
      - ./compose/certbot/conf/:/etc/letsencrypt/:rw # the certificate will be generated here

  web-api:
    container_name: "sharedshoppinglist-web_api"
    image: levos/sharedshoppinglist-web_api:latest
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__Default: Data Source=/db/shared-shopping-list.db;
    expose:
      - "80"
    volumes:
      - ./data/:/db/
