//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface CreateShoppingListEntryDto {
    name: string | undefined;
    quantity: string | undefined;
}

export interface CreateUserGroupDto {
    name: string | undefined;
}

export interface ErrorViewModel {
    message: string | undefined;
    errors: string[] | undefined;
    stackTrace: string | undefined;
}

export interface InviteCodeViewModel {
    value: string | undefined;
}

export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export interface RefreshTokenDto {
    accessToken: string | undefined;
    refreshToken: string | undefined;
}

export interface RegisterDto {
    username: string | undefined;
    password: string | undefined;
}

export interface ShoppingListEntryViewModel {
    id: number;
    name: string | undefined;
    quantity: string | undefined;
}

export interface ShoppingListEntryViewModelPaginatedListViewModel {
    pageIndex: number;
    totalPages: number;
    hasPreviousPage: boolean;
    hasNextPage: boolean;
    items: ShoppingListEntryViewModel[] | undefined;
}

export interface SignInDto {
    username: string | undefined;
    password: string | undefined;
}

export interface SignOutDto {
    refreshToken: string | undefined;
}

export interface TokenViewModel {
    accessToken: string | undefined;
    refreshToken: string | undefined;
    accessTokenExpiryTime: Date;
}

export interface UpdateShoppingListEntryDto {
    name: string | undefined;
    quantity: string | undefined;
}

export interface UpdateUserGroupDto {
    name: string | undefined;
}

export interface UserGroupViewModel {
    id: number;
    name: string | undefined;
    memberCount: number;
}

export interface UserGroupViewModelPaginatedListViewModel {
    pageIndex: number;
    totalPages: number;
    hasPreviousPage: boolean;
    hasNextPage: boolean;
    items: UserGroupViewModel[] | undefined;
}

export interface UserViewModel {
    id: string | undefined;
    username: string | undefined;
    groupMembershipCount: number;
}

export interface UserViewModelPaginatedListViewModel {
    pageIndex: number;
    totalPages: number;
    hasPreviousPage: boolean;
    hasNextPage: boolean;
    items: UserViewModel[] | undefined;
}